### ISSUE TITLE
Not a issue, just a recomendation

### ISSUE THREAD

**Issue by csenjoyer1337** [0x178F/YandexMail-Account-Creator#1]
Hello, i find this tool its really great, but could you please add capmonster.cloud if possible? Its 3 times cheaper than 2captcha, and yesteday when i created around 70 accounts, the 2captcha says ive done 190 captchas? Weird, but still this tool is great. Oh, and also add smtp enable is possible with 5sim/sms-activate. This tool is rlly great tho. Thanks :)

**Comment by 0x178F** [comment]
Hello, thanks for your recommendation. I'll check the Capmonster API documentation and add it soon if appropriate. I guess 2captcha might be counting the failed ones as well. But don't worry, I'm reporting them.

**Comment by csenjoyer1337** [comment]
Thank you! :) Have a great day

**Comment by 0x178F** [comment]
> Thank you! :) Have a great day

I added and published. I liked the Capmonster service it's very fast. But the accuracy rate is lower. I think they did this with machine learning. 
Have a nice day. 👍
