### ISSUE TITLE
cannot create mails

### ISSUE THREAD

**Issue by ghost** [0x178F/YandexMail-Account-Creator#5]
I get this error message after the captcha solving.

[CapMonster] - ERROR_KEY_DOES_NOT_EXIST

**Comment by 0x178F** [comment]
Have you configured the api key you received via CapMonster?

**Comment by Greg43V** [comment]
Hi, im having an issue where the captcha is on a constant loop. It says succesful captcha and then starts again and keeps going over and over. Any suggestions?
